/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.Werknemers;
import domain.ELoginTypeWerknemer;
import javax.swing.BorderFactory;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Kevin
 */
public class hoofdMenu extends javax.swing.JFrame {

    /**
     * Creates new form menuAdmin
     */
    Werknemers test = new Werknemers();

    public hoofdMenu() {
        initComponents();

        test.setNaam("Rose");
        test.setFunctie(ELoginTypeWerknemer.bediende);
        TitledBorder title;

        if (test.getFunctie().equals(ELoginTypeWerknemer.bediende)) {
            title = BorderFactory.createTitledBorder("welkom admin: " + test.getNaam());

        } else {
            title = BorderFactory.createTitledBorder("welkom gebruiker: " + test.getNaam());
            btnAankopenArtikelen.setVisible(false);
        }
        pnlAdmin.setBorder(title);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        btnAankopenArtikelen = new javax.swing.JButton();
        btnReservatieKlant = new javax.swing.JButton();
        btnVerkopenArtikelen = new javax.swing.JButton();
        btnStockArtikelen = new javax.swing.JButton();
        btnKlantToevoegen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));

        pnlAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin"));
        pnlAdmin.setPreferredSize(new java.awt.Dimension(1080, 720));

        btnAankopenArtikelen.setText("Aankopen Artikelen ");
        btnAankopenArtikelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAankopenArtikelenActionPerformed(evt);
            }
        });

        btnReservatieKlant.setText("Reservatie Klant");
        btnReservatieKlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservatieKlantActionPerformed(evt);
            }
        });

        btnVerkopenArtikelen.setText("Verkopen Artikelen");
        btnVerkopenArtikelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerkopenArtikelenActionPerformed(evt);
            }
        });

        btnStockArtikelen.setText("Stock Artikelen");
        btnStockArtikelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockArtikelenActionPerformed(evt);
            }
        });

        btnKlantToevoegen.setText("Klantenbeheer");
        btnKlantToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlantToevoegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerkopenArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAankopenArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStockArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKlantToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(btnReservatieKlant, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAankopenArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReservatieKlant, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKlantToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerkopenArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStockArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerkopenArtikelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerkopenArtikelenActionPerformed
        tegelVerkopen v = new tegelVerkopen(test);
        v.setVisible(true);//displays tegelVerkopen hier
        dispose(); //sluit huidige jframe na het openen TegelVerkopen   
    }//GEN-LAST:event_btnVerkopenArtikelenActionPerformed

    private void btnAankopenArtikelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAankopenArtikelenActionPerformed
        tegelAankopenArtikelen a = new tegelAankopenArtikelen(test);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAankopenArtikelenActionPerformed

    private void btnKlantToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlantToevoegenActionPerformed
        tegelKlantToevoegen k = new tegelKlantToevoegen(test);
        k.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKlantToevoegenActionPerformed

    private void btnReservatieKlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservatieKlantActionPerformed
        tegelReservatieKlant r = new tegelReservatieKlant(test);
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReservatieKlantActionPerformed

    private void btnStockArtikelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockArtikelenActionPerformed
        tegelArtikelenOpzoeken o = new tegelArtikelenOpzoeken(test);
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStockArtikelenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoofdMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoofdMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoofdMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoofdMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoofdMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAankopenArtikelen;
    private javax.swing.JButton btnKlantToevoegen;
    private javax.swing.JButton btnReservatieKlant;
    private javax.swing.JButton btnStockArtikelen;
    private javax.swing.JButton btnVerkopenArtikelen;
    private javax.swing.JPanel pnlAdmin;
    // End of variables declaration//GEN-END:variables
}
