/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.Werknemers;

/**
 *
 * @author Kevin
 */
public class menuWerknemer extends javax.swing.JFrame {

    /**
     * Creates new form menuWerknemer
     */
    public menuWerknemer() {

    }

    menuWerknemer(Werknemers w) {
        initComponents();
        setTitle(w.getNaam());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlWerknemer = new javax.swing.JPanel();
        btnReservatieKlant = new javax.swing.JButton();
        btnVerkopenArtikelen = new javax.swing.JButton();
        btnStockArtikelen = new javax.swing.JButton();
        btnKlantToevoegen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 720));

        pnlWerknemer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnlWerknemer.setPreferredSize(new java.awt.Dimension(1080, 720));

        btnReservatieKlant.setText("Reservatie Klant");
        btnReservatieKlant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservatieKlantActionPerformed(evt);
            }
        });

        btnVerkopenArtikelen.setText("Verkopen Artikelen");
        btnVerkopenArtikelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerkopenArtikelenActionPerformed(evt);
            }
        });

        btnStockArtikelen.setText("Stock Artikelen");
        btnStockArtikelen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockArtikelenActionPerformed(evt);
            }
        });

        btnKlantToevoegen.setText("Klant Toevoegen");
        btnKlantToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlantToevoegenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlWerknemerLayout = new javax.swing.GroupLayout(pnlWerknemer);
        pnlWerknemer.setLayout(pnlWerknemerLayout);
        pnlWerknemerLayout.setHorizontalGroup(
            pnlWerknemerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWerknemerLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(pnlWerknemerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerkopenArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKlantToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(pnlWerknemerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReservatieKlant, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStockArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(119, 119, 119))
        );
        pnlWerknemerLayout.setVerticalGroup(
            pnlWerknemerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWerknemerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlWerknemerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservatieKlant, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKlantToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(pnlWerknemerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerkopenArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStockArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlWerknemer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlWerknemer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerkopenArtikelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerkopenArtikelenActionPerformed
        tegelVerkopen v = new tegelVerkopen();
        v.setVisible(true); //displays tegelVerkopen hier
        dispose(); //sluit huidige jframe na het openen TegelVerkopen
    }//GEN-LAST:event_btnVerkopenArtikelenActionPerformed

    private void btnKlantToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlantToevoegenActionPerformed
        tegelKlantToevoegen k = new tegelKlantToevoegen();
        k.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKlantToevoegenActionPerformed

    private void btnReservatieKlantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservatieKlantActionPerformed
        tegelReservatieKlant r = new tegelReservatieKlant();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnReservatieKlantActionPerformed

    private void btnStockArtikelenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockArtikelenActionPerformed
        tegelArtikelenOpzoeken o = new tegelArtikelenOpzoeken();
        o.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnStockArtikelenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuWerknemer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuWerknemer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuWerknemer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuWerknemer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuWerknemer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlantToevoegen;
    private javax.swing.JButton btnReservatieKlant;
    private javax.swing.JButton btnStockArtikelen;
    private javax.swing.JButton btnVerkopenArtikelen;
    private javax.swing.JPanel pnlWerknemer;
    // End of variables declaration//GEN-END:variables
}
