/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ArtikelenDAO;
import dao.KlantenDAO;
import dao.OrdersDAO;
import db.*;
import domain.EStatus;
import domain.EmailService;
import domain.StuurMail;
import org.apache.log4j.Logger;

import javax.swing.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;

/**
 *
 * @author Kevin
 */
public class tegelReservatieKlant extends javax.swing.JFrame {

    private static final Logger LOG = Logger.getLogger(LoginFrame.class);

    private DefaultListModel<Klanten> mdlKlanten;
    private DefaultListModel<Artikelen> mdlArtikelen;
    public ArrayList<Artikelen> artLijst;
    private Orders order;
    private EmailService emailService;

    public tegelReservatieKlant(Werknemers w) {
        initComponents();
        setTitle(w.getNaam());
        artLijst = new ArrayList<Artikelen>();
        this.emailService = new EmailService();
    }

    tegelReservatieKlant() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlTop = new javax.swing.JPanel();
        btnHoofdMenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pnlZoeken = new javax.swing.JPanel();
        txfNaam = new javax.swing.JTextField();
        txfEmail = new javax.swing.JTextField();
        txfTelefoon = new javax.swing.JTextField();
        btnOpzoeken = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        scpKlanten = new javax.swing.JScrollPane();
        lstGevondenKlanten = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        lblKlantMessage = new javax.swing.JLabel();
        pnlKlanten = new javax.swing.JPanel();
        txfArtikelToevoegen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnToevoegen = new javax.swing.JButton();
        scpLijstArtikelen = new javax.swing.JScrollPane();
        lstArtikelenLijst = new javax.swing.JList<>();
        btnReservatieMaken = new javax.swing.JButton();
        txtAaantal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdbGeleverd = new javax.swing.JRadioButton();
        rdbNietGeleverd = new javax.swing.JRadioButton();
        btnRerservatieLijst = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txfArtikelOmschrijving = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnHoofdMenu.setText("terug naar hoofdmenu");
        btnHoofdMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoofdMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHoofdMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHoofdMenu)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTop, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservatie Klanten"));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));

        pnlZoeken.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnOpzoeken.setText("opzoeken");
        btnOpzoeken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpzoekenActionPerformed(evt);
            }
        });

        jLabel1.setText("Zoek hier de klant op:");

        jLabel2.setText("naam:");

        jLabel3.setText("tel nr:");

        jLabel4.setText("e-mail:");

        btnClear.setText("Wis Velden");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lstGevondenKlanten.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGevondenKlantenValueChanged(evt);
            }
        });
        scpKlanten.setViewportView(lstGevondenKlanten);

        jLabel9.setText("Selecteer de klant uit de lijst");

        lblKlantMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlZoekenLayout = new javax.swing.GroupLayout(pnlZoeken);
        pnlZoeken.setLayout(pnlZoekenLayout);
        pnlZoekenLayout.setHorizontalGroup(
            pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZoekenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pnlZoekenLayout.createSequentialGroup()
                        .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnOpzoeken, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlZoekenLayout.createSequentialGroup()
                                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNaam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfTelefoon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblKlantMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scpKlanten, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167))
        );
        pnlZoekenLayout.setVerticalGroup(
            pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZoekenLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnlZoekenLayout.createSequentialGroup()
                        .addComponent(txfNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTelefoon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(pnlZoekenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOpzoeken, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKlantMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZoekenLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpKlanten, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlKlanten.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("Voeg hier de artikelen toe met het artikel nummer, aan de hand van de tegel \"Artikelen Opzoeken\"");

        jLabel12.setText("Artikel Id:");

        btnToevoegen.setText("Artikel toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        scpLijstArtikelen.setViewportView(lstArtikelenLijst);

        btnReservatieMaken.setText("Reservatie Opslaan");
        btnReservatieMaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservatieMakenActionPerformed(evt);
            }
        });

        jLabel5.setText("Aantal:");

        buttonGroup1.add(rdbGeleverd);
        rdbGeleverd.setText("Geleverd");

        buttonGroup1.add(rdbNietGeleverd);
        rdbNietGeleverd.setText("Niet-Geleverd");

        btnRerservatieLijst.setText("Reservatie Aanmaken");
        btnRerservatieLijst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRerservatieLijstActionPerformed(evt);
            }
        });

        jLabel13.setText("Artikel omschrijving:");

        txfArtikelOmschrijving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfArtikelOmschrijvingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlKlantenLayout = new javax.swing.GroupLayout(pnlKlanten);
        pnlKlanten.setLayout(pnlKlantenLayout);
        pnlKlantenLayout.setHorizontalGroup(
            pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKlantenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlKlantenLayout.createSequentialGroup()
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(pnlKlantenLayout.createSequentialGroup()
                                .addComponent(rdbGeleverd)
                                .addGap(18, 18, 18)
                                .addComponent(rdbNietGeleverd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlKlantenLayout.createSequentialGroup()
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlKlantenLayout.createSequentialGroup()
                                .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRerservatieLijst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnToevoegen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(pnlKlantenLayout.createSequentialGroup()
                                .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAaantal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfArtikelOmschrijving, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfArtikelToevoegen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(scpLijstArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReservatieMaken, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        pnlKlantenLayout.setVerticalGroup(
            pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlKlantenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlKlantenLayout.createSequentialGroup()
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scpLijstArtikelen, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReservatieMaken, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(pnlKlantenLayout.createSequentialGroup()
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txfArtikelToevoegen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txfArtikelOmschrijving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnToevoegen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAaantal))
                        .addGap(18, 18, 18)
                        .addGroup(pnlKlantenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbNietGeleverd)
                            .addComponent(rdbGeleverd))
                        .addGap(18, 18, 18)
                        .addComponent(btnRerservatieLijst)
                        .addGap(39, 39, 39))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlZoeken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlKlanten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(pnlZoeken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(pnlKlanten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoofdMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoofdMenuActionPerformed
        hoofdMenu a = new hoofdMenu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHoofdMenuActionPerformed

    private void btnOpzoekenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpzoekenActionPerformed
        String klantnaam = txfNaam.getText();
        String gsm = txfTelefoon.getText();
        String email = txfEmail.getText();

        KlantenDAO k = new KlantenDAO();
        List<Klanten> resultaat = new ArrayList();
        System.out.println(klantnaam + ", " + gsm + " ," + email);
        if (!klantnaam.equals("")) {
            lblKlantMessage.setText(null);
            resultaat = k.zoekKlanten(klantnaam);
        } else if (!gsm.equals("")) {
            lblKlantMessage.setText(null);
            resultaat = k.zoekKlantenOpGsm(gsm);
        } else if (!email.equals("")) {
            lblKlantMessage.setText(null);
            resultaat = k.zoekKlantenOpEmail(email);
        } else {
            lblKlantMessage.setText("De opzoek velden mogen niet leeg zijn! Gelieve een van de velden in te vullen.");
        }
        System.out.println(resultaat);
        mdlKlanten = new DefaultListModel();
        for (Klanten klant : resultaat) {
            mdlKlanten.addElement(klant);
        }
        lstGevondenKlanten.setModel(mdlKlanten);

    }//GEN-LAST:event_btnOpzoekenActionPerformed

    private void lstGevondenKlantenValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGevondenKlantenValueChanged
        Klanten klant = lstGevondenKlanten.getSelectedValue();
        order = new Orders();
        order.setDatum(new Date());
        order.setKlant(klant);
    }//GEN-LAST:event_lstGevondenKlantenValueChanged

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearVelden();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnReservatieMakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservatieMakenActionPerformed
        Klanten klant = lstGevondenKlanten.getSelectedValue();
        List<Artikelen> artikel = lstArtikelenLijst.getSelectedValuesList();
        String aantalText = txtAaantal.getText();

        if (klant == null && artikel.isEmpty() && aantalText == "") {
            JOptionPane.showMessageDialog(this, "Klant, Artikel, en Aantal zijn verplicht te selecteren!", "Melding", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                List<Orderlijnen> lijn = order.getOrderlijnenList();
                order.setOrderlijnenList(lijn);
                OrdersDAO orderdb = new OrdersDAO();
                orderdb.VoegOrder(order);

                if (klant.getEmail() == null) {
                    JOptionPane.showMessageDialog(this, "Reservatie aangemaakt, *Geen Email verstuurd! De klant heeft geen email.", "Gelukt", JOptionPane.PLAIN_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Reservatie aangemaakt, De klant krijgt een bevestiging mail.", "Gelukt", JOptionPane.PLAIN_MESSAGE);
                    emailService.confirmReservatie(klant.getEmail(), order);
                }

                clearVelden();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Klant, Artikel, en Aantal zijn verplicht te selecteren!", "Melding", JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnReservatieMakenActionPerformed

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        Integer artikelId = null;
        try {

            if (txfArtikelToevoegen.getText() != null) {
                artikelId = Integer.parseInt(txfArtikelToevoegen.getText());
            }
        } catch (NumberFormatException ignored) {

        }

        ArtikelenDAO artikel = new ArtikelenDAO();

        Artikelen art = null;
        if (artikelId != null) {
            art = artikel.ArtikelOpzoeken(artikelId);
        }

        if (art == null) {
            String artikelCat = txfArtikelOmschrijving.getText();
            if (artikelCat != null) {
                List<Artikelen> list = artikel.ArtikelOpzoeken(artikelCat);
                artLijst.addAll(list);

            }
        } else {
            artLijst.add(art);
        }

        mdlArtikelen = new DefaultListModel();
        for (Artikelen s : artLijst) {
            mdlArtikelen.addElement(s);
        }
        lstArtikelenLijst.setModel(mdlArtikelen);
        artLijst.clear();
        txfArtikelToevoegen.setText(null);
        txfArtikelOmschrijving.setText(null);
    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void btnRerservatieLijstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRerservatieLijstActionPerformed
        // Reservaties van orders
        Klanten klant = lstGevondenKlanten.getSelectedValue();
        List<Artikelen> artikelen = lstArtikelenLijst.getSelectedValuesList();
        if (klant == null || artikelen.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Reservatie niet gemaakt. Klant,Artikelen zijn verplicht te selecteren", "NietGelukt", JOptionPane.PLAIN_MESSAGE);
        } else {
            List<Artikelen> artikelList = lstArtikelenLijst.getSelectedValuesList();
            for (Artikelen artikel : artikelList) {
                String aantalText = txtAaantal.getText();
                try {
                    int aantal = Integer.parseInt(aantalText);

                    Orderlijnen orderlijn = new Orderlijnen();
                    orderlijn.setAantal(aantal);
                    orderlijn.setArtikel(artikel);
                    orderlijn.setOrders(order);

                    orderlijn.setPrijs(artikel.getPrijs());

                    if (rdbGeleverd.isSelected()) {
                        orderlijn.setStatus(EStatus.geleverd);
                    } else if (rdbNietGeleverd.isSelected()) {
                        orderlijn.setStatus(EStatus.nietgeleverd);
                    }

                    boolean items = order.getOrderlijnenList().add(orderlijn);
                    LOG.info(items);
                    LOG.info("Orderlijst" + order.getOrderlijnenList().toString());

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Klant, Artikel, en Aantal zijn verplicht te selecteren!", "Melding", JOptionPane.PLAIN_MESSAGE);
                }
            }
            JOptionPane.showMessageDialog(this, "Reservatie aangemaakt en toegevoegd in winkelmandje.", "Gelukt", JOptionPane.PLAIN_MESSAGE);

            txtAaantal.setText(null);
        }
    }//GEN-LAST:event_btnRerservatieLijstActionPerformed

    private void txfArtikelOmschrijvingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfArtikelOmschrijvingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfArtikelOmschrijvingActionPerformed
    private void clearVelden() {
        txfNaam.setText(null);
        txtAaantal.setText(null);
        txfEmail.setText(null);
        txfTelefoon.setText(null);
        txfArtikelToevoegen.setText(null);
        txfArtikelOmschrijving.setText(null);

        int klantIndex = lstGevondenKlanten.getFirstVisibleIndex();
        if (klantIndex != -1) {
            mdlKlanten.remove(klantIndex);
            mdlKlanten.clear();
        }
        int artikelIndex = lstArtikelenLijst.getFirstVisibleIndex();
        if (artikelIndex != -1) {
            mdlArtikelen.remove(artikelIndex);
            mdlArtikelen.clear();
        }
        lblKlantMessage.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tegelReservatieKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tegelReservatieKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tegelReservatieKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tegelReservatieKlant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tegelReservatieKlant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHoofdMenu;
    private javax.swing.JButton btnOpzoeken;
    private javax.swing.JButton btnRerservatieLijst;
    private javax.swing.JButton btnReservatieMaken;
    private javax.swing.JButton btnToevoegen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKlantMessage;
    private javax.swing.JList<Artikelen> lstArtikelenLijst;
    private javax.swing.JList<Klanten> lstGevondenKlanten;
    private javax.swing.JPanel pnlKlanten;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlZoeken;
    private javax.swing.JRadioButton rdbGeleverd;
    private javax.swing.JRadioButton rdbNietGeleverd;
    private javax.swing.JScrollPane scpKlanten;
    private javax.swing.JScrollPane scpLijstArtikelen;
    private javax.swing.JTextField txfArtikelOmschrijving;
    private javax.swing.JTextField txfArtikelToevoegen;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfNaam;
    private javax.swing.JTextField txfTelefoon;
    private javax.swing.JTextField txtAaantal;
    // End of variables declaration//GEN-END:variables
}
